### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kilpkonn** [kilpkonn/KahootBot#1]
**TODO list:**
- [x] ~~**Make asyncronous input / run bots on separate thread(s)**~~
- [x] **Add help command**
- [x] **Use multiple threads for better performance**
- [x] **Better colors for print (?)**
- [x] ~~**Shut down bots that have bad score / fail to answer**~~
